name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Or "master", depending on your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # This assumes index.html is in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
